security:
    #access_control:
    #    - { path: ^/dashboard, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user:
        #                password: user
        #                roles: 'ROLE_USER'
        #            admin:
        #                password: admin
        #                roles: 'ROLE_ADMIN' 
        dbservice:
            id: app.dbservice_user_provider
        admin_dbservice:
            id: app.dbservice_admin_provider     

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Melodycode\FossdroidBundle\Security\User\DBServiceUser: plaintext
        Iris\DashboardBundle\Security\User\DBServiceUser: plaintext
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        admin:
            pattern:   ^/dashboard
            anonymous: ~
            provider: admin_dbservice
            form_login:
                login_path: /dashboard/login
                check_path: /dashboard/login
                default_target_path: /dashboard
                success_handler: app.admin.loginhandler 
                
            logout:
                path: /dashboard/logout
                target: /dashboard/     
                
        main:
            provider: dbservice 
            anonymous: ~
            form_login:
                login_path: login
                check_path: login 
                success_handler: app.loginhandler 
                 
            logout:
                path: /store/logout
                target: /store/         
        
        default:
            anonymous: ~
    role_hierarchy:
        ROLE_SUPER: [ROLE_DEVELOPMENT, ROLE_MARKETING, ROLE_RANDD]            